app/routes/web.php
<?php
Auth::routes();
Route::resource('contact', 'ContactController');
Route::get('/', 'ContactController@index');
Route::get('/home', 'ContactController@index');

app/app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
	protected $guarded = ['id'];

    public function email()
    {
    	return $this->belongsTo(Email::class);
    }

    public function phone()
    {
    	return $this->belongsTo(Phone::class);
    }

    public function person()
    {
    	return $this->belongsTo(Person::class);
    }
}

app/app/Email.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Email extends Model
{
	protected $guarded = ['id'];
	
    public function contact()
    {
    	return $this->belongsTo(Contact::class);
    }
}

app/app/Person.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
	protected $guarded = ['id'];
	
    public function contact()
    {
    	return $this->belongsTo(Contact::class);
    }
}

app/app/Phone.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Phone extends Model
{
	protected $guarded = ['id'];
	
    public function contact()
    {
    	return $this->belongsTo(Contact::class);
    }
}

app/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Contact;
use App\Phone;
use App\Email;
use App\Person;
use Auth;

class ContactController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts = Contact::orderBy('created_at', 'desc')->get();
        return view('contacts.index', compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::user()->admin){
            return view('contacts.create');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(Auth::user()->admin){

            $this->validate($request, 
                [
                'firstname' => 'required|min:3|max:10',
                'surname' => 'required|min:3|max:10',
                'emailaddress' => 'required|email|unique:emails,address',
                'phonenumber' => 'required|regex:/(0)[0-9]{10}/|unique:phones,number',
                ], []);

            $person = Person::create([
                'firstname' => $request->input('firstname'),
                'surname' => $request->input('surname'),
                ]);

            $email = Email::create(['address' => $request->input('emailaddress')]);
            $phone = Phone::create(['number' => $request->input('phonenumber')]);
            $contact = Contact::create([
                'person_id' => $person->id,
                'email_id' => $email->id,
                'phone_id' => $phone->id
                ]);
            return redirect()->route('contact.show', ['id' => $contact->id]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $contact = Contact::find($id);
        return $contact ? view('contacts.show', compact('contact')) : redirect('/');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::user()->admin){
            $contact = Contact::find($id);
            return $contact ? view('contacts.edit', compact('contact')) : redirect('/');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, 
            [
            'firstname' => 'required|min:3|max:10',
            'surname' => 'required|min:3|max:10',
            'emailaddress' => 'required|email',
            'phonenumber' => 'required|regex:/(0)[0-9]{10}/',
            ], []);

        $contact = Contact::find($id);
        Person::where('id', $contact->person_id)->update([
            'firstname' => $request->input('firstname'), 
            'surname' => $request->input('surname'), 
            ]);

        Email::where('id', $contact->email_id)->update([
            'address' => $request->input('emailaddress'),
            ]);

        Phone::where('id', $contact->phone_id)->update([
            'number' => $request->input('phonenumber'),
            ]);

        return redirect()->route('contact.show', ['id' => $id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Auth::user()->admin){
            $contact = Contact::find($id);
            $contact->delete();
            return redirect('/');
        }
    }
}

app/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/resources/views/contacts/create.blade.php
@extends('layouts.app')

@section('content')
@if(Auth::user()->admin)
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-default">
				<div class="panel-heading">Add a Contact</div>
				<div class="panel-body">
				@include('layouts.errors')
					<form method="POST" action="{{ route('contact.store') }}">
						{{csrf_field()}}
						<div class="form-group">
							<label>Firstname</label>
							<input type="text" class="form-control" id="firstname" name="firstname">
						</div>
						<div class="form-group">
							<label>Surname</label>
							<input type="text" class="form-control" id="surname" name="surname">
						</div>
						<div class="form-group">
							<label>Phone Number</label>
							<input type="text" class="form-control" id="phonenumber" name="phonenumber">
						</div>
						<div class="form-group">
							<label>Email Address</label>
							<input type="text" class="form-control" id="emailaddress" name="emailaddress">
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-primary">Create</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endif
@endsection

app/resources/views/contacts/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-default">
				<div class="panel-heading">Edit Contact</div>
				<div class="panel-body">
				@include('layouts.errors')
					<form method="POST" action="{{ route('contact.update', $contact->id) }}">
						{{method_field('PATCH')}}
						{{csrf_field()}}
						<div class="form-group">
							<label>Firstname</label>
							<input type="text" class="form-control" id="firstname" name="firstname" value="{{ $contact->person->firstname }}">
						</div>
						<div class="form-group">
							<label>Surname</label>
							<input type="text" class="form-control" id="surname" name="surname" value="{{ $contact->person->surname }}">
						</div>
						<div class="form-group">
							<label>Phone Number</label>
							<input type="text" class="form-control" id="phonenumber" name="phonenumber" value="{{ $contact->phone->number }}">
						</div>
						<div class="form-group">
							<label>Email Address</label>
							<input type="text" class="form-control" id="emailaddress" name="emailaddress" value="{{ $contact->email->address }}">
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-primary">Update</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

app/resources/views/contacts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-default">
				<div class="panel-heading">Contacts</div>
				<div class="panel-body">
				@if(Auth::user()->admin)
				<a class="btn btn-xs btn-primary" href="{{ url('contact/create')}}">New Contact</a>
				@endif
					@include('layouts.errors')
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Full Name</th>
								<th>Phone Number</th>
								<th>Email Address</th>
								@if(Auth::user()->admin)
								<th></th>
								<th></th>
								@endif
							</tr>
						</thead>
						<tbody>
							@foreach($contacts as $contact)
							<tr>
								<td>{{$contact->person->firstname}} {{$contact->person->surname}}</td>
								<td>{{$contact->phone->number}}</td>
								<td>{{$contact->email->address}}</td>
								@if(Auth::user()->admin)
								<td><a class="btn btn-xs btn-warning" href="{{ route('contact.edit', $contact->id) }}">Edit</a></td>
								<td>
									<a href="#" class="btn btn-xs btn-danger" onclick="$(this).find('form').submit();">
										Delete
										<form action="/app/contact/{{ $contact->id }}" method="POST">
											<input type="hidden" name="_method" value="DELETE">
											{{csrf_field()}}
										</form>
									</a>
								</td>
								@endif
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
@endsection

app/resources/views/contacts/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-default">
				<div class="panel-heading">Contacts</div>
				<div class="panel-body">
					<a href="/app" class="btn btn-xs btn-primary">See All</a>
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Full Name</th>
								<th>Phone Number</th>
								<th>Email Address</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>{{$contact->person->firstname}} {{$contact->person->surname}}</td>
								<td>{{$contact->phone->number}}</td>
								<td>{{$contact->email->address}}</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
@endsection

app/resources/views/home.blade.php
@extends('layouts.app')

@section('content')

@endsection

app/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>My Address Book</title>

    <!-- Styles -->
    <link href="{{ asset('public/css/theme.min.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        My Address Book
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('public/js/app.js') }}"></script>
</body>
</html>

app/resources/views/layouts/errors.blade.php
@if($errors->all())
	<div class="alert alert-danger">
	@foreach($errors->all() as $error)
	<li>{{$error}}</li>
	@endforeach
	</div>
@endif